import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:hugeicons/hugeicons.dart';

import '../../../../core/di/injection.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/ui/widgets/desktop_status_bar.dart';
import '../../data/datasources/production_batch_remote_datasource.dart';
import '../../domain/entities/production_batch_entity.dart';
import '../bloc/production_batch_form_bloc.dart';
import '../bloc/production_batch_form_event.dart';
import '../bloc/production_batch_form_state.dart';
import '../widgets/machine_picker_bottom_sheet.dart';
import '../widgets/order_picker_bottom_sheet.dart';
import '../widgets/production_batch_form_controller.dart';
import '../widgets/production_batch_form_item_row.dart';
import '../widgets/production_batch_form_table_header.dart';
import '../widgets/production_batch_form_total_chip.dart';

/// Unified entrypoint for both add and edit production batch flows.
///
/// Pass [batch] to enter edit mode (pre-fills form, submits an update).
/// Omit [batch] (or pass null) to enter add mode (empty form, creates new).
class ProductionBatchFormPage extends StatefulWidget {
  const ProductionBatchFormPage({super.key, this.batch});

  /// When non-null the form operates in edit mode.
  final ProductionBatchEntity? batch;

  @override
  State<ProductionBatchFormPage> createState() =>
      _ProductionBatchFormPageState();
}

class _ProductionBatchFormPageState extends State<ProductionBatchFormPage> {
  late final ProductionBatchFormController _ctrl;
  ProductionBatchEntity? _fullBatch;
  bool _loading = false;

  @override
  void initState() {
    super.initState();
    _ctrl = ProductionBatchFormController();
    if (widget.batch != null) {
      _fetchFullBatch(widget.batch!);
    }
  }

  Future<void> _fetchFullBatch(ProductionBatchEntity partial) async {
    setState(() => _loading = true);
    try {
      final full = await sl<ProductionBatchRemoteDataSource>()
          .getProductionBatch(partial.id);
      if (!mounted) return;
      _ctrl.loadFromBatch(full);
      setState(() {
        _fullBatch = full;
        _loading = false;
      });
    } catch (_) {
      if (mounted) setState(() => _loading = false);
    }
  }

  @override
  void dispose() {
    _ctrl.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (widget.batch != null && _loading) {
      return Scaffold(
        appBar: AppBar(title: const Text('Tahrirlash...')),
        body: const Center(child: CircularProgressIndicator()),
      );
    }

    final effectiveBatch = _fullBatch ?? widget.batch;

    return BlocProvider(
      create: (_) => sl<ProductionBatchFormBloc>(),
      child: _ProductionBatchFormBody(
        controller: _ctrl,
        initialBatch: effectiveBatch,
      ),
    );
  }
}

// ── Form body ─────────────────────────────────────────────────────────────────

class _ProductionBatchFormBody extends StatefulWidget {
  const _ProductionBatchFormBody({
    required this.controller,
    this.initialBatch,
  });

  final ProductionBatchFormController controller;

  /// When non-null the form is in edit mode.
  final ProductionBatchEntity? initialBatch;

  @override
  State<_ProductionBatchFormBody> createState() =>
      _ProductionBatchFormBodyState();
}

class _ProductionBatchFormBodyState extends State<_ProductionBatchFormBody> {
  final _formKey = GlobalKey<FormState>();

  ProductionBatchMachine? _selectedMachine;

  // ── Client (derived from imported order) ────────────────────────────────
  int? _selectedClientId;
  String? _selectedClientName;

  bool get _isEditMode => widget.initialBatch != null;

  ProductionBatchMachine? get _effectiveMachine =>
      _selectedMachine ?? widget.initialBatch?.machine;

  String get _machineDisplay => _effectiveMachine?.name ?? 'Stanok tanlash...';

  bool get _hasMachine => _effectiveMachine != null;

  /// Auto-generates batch title based on client and machine
  String get _autoGeneratedTitle {
    final clientPart = _selectedClientName ?? 'Omborga';
    final machinePart = _effectiveMachine?.name;
    return machinePart != null ? '$clientPart | $machinePart' : clientPart;
  }

  @override
  void initState() {
    super.initState();
    final batch = widget.initialBatch;
    if (batch != null) {
      widget.controller.notesCtrl.text = batch.notes ?? '';
    }
  }

  Future<void> _pickMachine() async {
    final machine = await MachinePickerBottomSheet.show(context);
    if (machine != null && mounted) {
      setState(() => _selectedMachine = machine);
    }
  }

  /// Re-derives client from the current filled rows that were imported from an
  /// order. If no such rows remain, clears the client.
  void _syncClientFromItems() {
    final orderRows = widget.controller.items
        .where((r) => r.isFilled && r.sourceClientName != null)
        .toList();
    setState(() {
      if (orderRows.isEmpty) {
        _selectedClientId = null;
        _selectedClientName = null;
      } else {
        _selectedClientName = orderRows.first.sourceClientName;
      }
    });
  }

  String get _plannedDateStr {
    final now = DateTime.now();
    return '${now.year}-${now.month.toString().padLeft(2, '0')}-${now.day.toString().padLeft(2, '0')}T${now.hour.toString().padLeft(2, '0')}:${now.minute.toString().padLeft(2, '0')}:00';
  }

  void _submit() {
    if (!_formKey.currentState!.validate()) return;

    if (!_hasMachine) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Stanokni tanlash shart.'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    final ctrl = widget.controller;
    final title = _autoGeneratedTitle; // Auto-generated title
    final notes =
        ctrl.notesCtrl.text.trim().isEmpty ? null : ctrl.notesCtrl.text.trim();
    final items = ctrl.buildItemsPayload();

    if (_isEditMode) {
      context.read<ProductionBatchFormBloc>().add(
            ProductionBatchFormUpdateSubmitted(
              batchId: widget.initialBatch!.id,
              batchTitle: title,
              machineId: _effectiveMachine!.id,
              plannedDatetime: _plannedDateStr,
              type: ctrl.computedType,
              notes: notes,
              items: items.isEmpty ? null : items,
            ),
          );
    } else {
      context.read<ProductionBatchFormBloc>().add(
            ProductionBatchFormSubmitted(
              batchTitle: title,
              machineId: _effectiveMachine!.id,
              plannedDatetime: _plannedDateStr,
              type: ctrl.computedType,
              notes: notes,
              items: items.isEmpty ? null : items,
            ),
          );
    }
  }

  @override
  Widget build(BuildContext context) {
    return BlocListener<ProductionBatchFormBloc, ProductionBatchFormState>(
      listener: (context, state) {
        if (state is ProductionBatchFormSuccess) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                _isEditMode ? 'Partiya yangilandi.' : 'Partiya saqlandi.',
              ),
              backgroundColor: AppColors.success,
            ),
          );
          context.pop(true);
        } else if (state is ProductionBatchFormFailure) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(state.message),
              backgroundColor: AppColors.error,
            ),
          );
        }
      },
      child: ListenableBuilder(
        listenable: widget.controller,
        builder: (context, _) {
          final ctrl = widget.controller;
          return Scaffold(
            backgroundColor: AppColors.background,
            appBar: AppBar(
              title: Text(
                _isEditMode
                    ? '#${widget.initialBatch!.id} Tahrirlash'
                    : 'Yangi ishlab chiqarish',
              ),
              titleSpacing: 0,
              leading: IconButton(
                icon: const HugeIcon(
                  icon: HugeIcons.strokeRoundedArrowLeft01,
                  strokeWidth: 2,
                ),
                onPressed: () => context.pop(),
              ),
              actions: [
                BlocBuilder<ProductionBatchFormBloc, ProductionBatchFormState>(
                  builder: (context, state) {
                    if (state is ProductionBatchFormSubmitting) {
                      return const Padding(
                        padding: EdgeInsets.symmetric(horizontal: 16),
                        child: Center(
                          child: SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(
                              strokeWidth: 2,
                              color: AppColors.background,
                            ),
                          ),
                        ),
                      );
                    }
                    return FilledButton(
                      onPressed: _submit,
                      child: const Text('Saqlash'),
                    );
                  },
                ),
                const SizedBox(width: 16),
              ],
            ),
            body: Form(
              key: _formKey,
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  // ── Top info bar ──────────────────────────────────────────
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 12, vertical: 12),
                    decoration: const BoxDecoration(
                      color: AppColors.surface,
                      border:
                          Border(bottom: BorderSide(color: AppColors.divider)),
                    ),
                    child: Row(
                      children: [
                        // Type badge
                        Container(
                          height: 40,
                          padding: const EdgeInsets.symmetric(horizontal: 12),
                          decoration: BoxDecoration(
                            color: ctrl.computedType == 'for_stock'
                                ? AppColors.success.withValues(alpha: 0.1)
                                : ctrl.computedType == 'by_order'
                                    ? AppColors.primary.withValues(alpha: 0.1)
                                    : AppColors.warning.withValues(alpha: 0.1),
                            borderRadius: BorderRadius.circular(8),
                            border: Border.all(
                              color: ctrl.computedType == 'for_stock'
                                  ? AppColors.success
                                  : ctrl.computedType == 'by_order'
                                      ? AppColors.primary
                                      : AppColors.warning,
                              width: 1.5,
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(
                                ctrl.computedType == 'for_stock'
                                    ? Icons.warehouse_outlined
                                    : ctrl.computedType == 'by_order'
                                        ? Icons.receipt_long_outlined
                                        : Icons.inventory_2_outlined,
                                size: 16,
                                color: ctrl.computedType == 'for_stock'
                                    ? AppColors.success
                                    : ctrl.computedType == 'by_order'
                                        ? AppColors.primary
                                        : AppColors.warning,
                              ),
                              const SizedBox(width: 8),
                              Text(
                                ctrl.computedType == 'for_stock'
                                    ? 'Omborga'
                                    : ctrl.computedType == 'by_order'
                                        ? _selectedClientName ?? 'Buyurtma'
                                        : 'Aralash',
                                style: Theme.of(context)
                                    .textTheme
                                    .bodyMedium
                                    ?.copyWith(
                                      color: ctrl.computedType == 'for_stock'
                                          ? AppColors.success
                                          : ctrl.computedType == 'by_order'
                                              ? AppColors.primary
                                              : AppColors.warning,
                                      fontWeight: FontWeight.w600,
                                    ),
                              ),
                            ],
                          ),
                        ),
                        const SizedBox(width: 12),
                        // Machine picker
                        Expanded(
                          child: InkWell(
                            onTap: _pickMachine,
                            borderRadius: BorderRadius.circular(8),
                            child: Container(
                              height: 40,
                              padding:
                                  const EdgeInsets.symmetric(horizontal: 12),
                              decoration: BoxDecoration(
                                border: Border.all(
                                  color: !_hasMachine
                                      ? AppColors.divider
                                      : AppColors.primary,
                                  width: !_hasMachine ? 1.0 : 1.5,
                                ),
                                borderRadius: BorderRadius.circular(8),
                                color: _hasMachine
                                    ? AppColors.primary.withValues(alpha: 0.05)
                                    : null,
                              ),
                              child: Row(
                                children: [
                                  Icon(
                                    Icons.precision_manufacturing_outlined,
                                    size: 16,
                                    color: !_hasMachine
                                        ? AppColors.textSecondary
                                        : AppColors.primary,
                                  ),
                                  const SizedBox(width: 8),
                                  Expanded(
                                    child: Text(
                                      _machineDisplay,
                                      style: Theme.of(context)
                                          .textTheme
                                          .bodyMedium
                                          ?.copyWith(
                                            color: !_hasMachine
                                                ? AppColors.textSecondary
                                                : null,
                                          ),
                                      overflow: TextOverflow.ellipsis,
                                    ),
                                  ),
                                  if (_selectedMachine != null)
                                    GestureDetector(
                                      onTap: () {
                                        setState(() => _selectedMachine = null);
                                      },
                                      child: const Icon(Icons.close,
                                          size: 18,
                                          color: AppColors.textSecondary),
                                    ),
                                ],
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),

                  // ── Items section label ───────────────────────────────────
                  Row(
                    children: [
                      Expanded(
                        child: Padding(
                          padding: const EdgeInsets.fromLTRB(12, 12, 24, 8),
                          child: Text(
                            'Mahsulotlar',
                            style: Theme.of(context)
                                .textTheme
                                .titleSmall
                                ?.copyWith(
                                  color: AppColors.primary,
                                  fontWeight: FontWeight.w600,
                                ),
                          ),
                        ),
                      ),
                      Padding(
                        padding: const EdgeInsets.fromLTRB(0, 4, 12, 4),
                        child: TextButton.icon(
                          onPressed: () async {
                            final result = await OrderPickerBottomSheet.show(
                              context,
                              clientId: _selectedClientId,
                            );
                            if (result != null && mounted) {
                              ctrl.addRowsFromOrder(result.order, result.items);
                              setState(() {
                                _selectedClientId = result.order.clientId;
                                _selectedClientName =
                                    result.order.clientShopName ??
                                        result.order.userName;
                              });
                            }
                          },
                          icon: const Icon(Icons.download_rounded, size: 16),
                          label: const Text('Buyurtmadan import'),
                        ),
                      ),
                    ],
                  ),

                  // ── Table header ──────────────────────────────────────────
                  const ProductionBatchFormTableHeader(),
                  const Divider(height: 1, color: AppColors.divider),

                  // ── Table rows ────────────────────────────────────────────
                  Expanded(
                    child: ListView.separated(
                      padding: EdgeInsets.zero,
                      itemCount: ctrl.items.length,
                      separatorBuilder: (_, __) =>
                          const Divider(height: 1, color: AppColors.divider),
                      itemBuilder: (context, index) {
                        final row = ctrl.items[index];
                        return ProductionBatchFormItemRow(
                          key: ValueKey(row.id),
                          row: row,
                          allItems: ctrl.items,
                          index: index,
                          onRemove: () {
                            ctrl.removeRow(row);
                            _syncClientFromItems();
                          },
                          onChanged: () {
                            ctrl.promoteIfSentinel(row);
                            ctrl.updateRow(row);
                          },
                        );
                      },
                    ),
                  ),
                  const Divider(height: 1, color: AppColors.divider),

                  // ── Notes ─────────────────────────────────────────────────
                  Container(
                    padding: const EdgeInsets.symmetric(
                        horizontal: 12, vertical: 12),
                    child: TextFormField(
                      controller: ctrl.notesCtrl,
                      maxLines: 2,
                      decoration: const InputDecoration(
                        labelText: 'Izoh (ixtiyoriy)',
                        hintText: "Qo'shimcha ma'lumot...",
                        alignLabelWithHint: true,
                      ),
                    ),
                  ),

                  // ── Status bar ────────────────────────────────────────────
                  Builder(builder: (context) {
                    final filled = ctrl.items.where((r) => r.isFilled).toList();
                    final totalQty = filled.fold(
                      0,
                      (sum, r) =>
                          sum + (int.tryParse(r.quantityCtrl.text) ?? 1),
                    );
                    final totalSqm = filled.fold(0.0, (sum, r) {
                      final qty = int.tryParse(r.quantityCtrl.text) ?? 1;
                      if (r.selectedSize != null) {
                        return sum +
                            r.selectedSize!.length *
                                r.selectedSize!.width *
                                qty /
                                10000.0;
                      }
                      if (r.prefilledSizeLength != null &&
                          r.prefilledSizeWidth != null) {
                        return sum +
                            r.prefilledSizeLength! *
                                r.prefilledSizeWidth! *
                                qty /
                                10000.0;
                      }
                      return sum;
                    });
                    return DesktopStatusBar(
                      child: Row(
                        children: [
                          ProductionBatchFormTotalChip(
                              label: 'Mahsulotlar', value: '${filled.length}'),
                          const SizedBox(width: 16),
                          ProductionBatchFormTotalChip(
                              label: 'Jami dona', value: '$totalQty'),
                          const SizedBox(width: 16),
                          ProductionBatchFormTotalChip(
                              label: 'Jami m²',
                              value: '${totalSqm.toStringAsFixed(2)} m²'),
                        ],
                      ),
                    );
                  }),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}
